### ISSUE TITLE
iOS development build issue

### ISSUE THREAD

**Issue by yamaha252** [Jumio/mobile-flutter#20] opened 2021-12-27 13:34 UTC
Hello!
After installing Jumio flutter mobile SDK using `flutter pub add jumio_mobile_sdk_flutter`, ios development running stops working.
I see following errors:

```
Launching lib/main_personal_dev.dart on iPhone 12 in debug mode...
Running Xcode build...
Xcode build done.                                            8.9s
Failed to build iOS app
Error output from Xcode build:
↳
    --- xcodebuild: WARNING: Using the first of multiple matching destinations:
    { platform:iOS Simulator, id:dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator:placeholder, name:Any iOS Simulator Device }
    { platform:iOS Simulator, id:947C7759-D475-4210-84FE-EA1C11B1AEFD, OS:15.2, name:iPhone 8 }
    { platform:iOS Simulator, id:08EEE0F0-D8C0-446A-ABD5-7FB97F56CA0A, OS:15.2, name:iPhone 8 Plus }
    { platform:iOS Simulator, id:26610465-93B7-41F1-822C-CFF6B08D9CA2, OS:15.2, name:iPhone 11 }
    { platform:iOS Simulator, id:4C279543-2981-4C3C-890F-2B1081513E56, OS:15.2, name:iPhone 11 Pro }
    { platform:iOS Simulator, id:5C03F194-629A-4FF1-9C80-18666BAF0C80, OS:15.2, name:iPhone 11 Pro Max }
    { platform:iOS Simulator, id:6DCABE5C-AB61-4AE1-884F-8F22EE0AA34D, OS:15.2, name:iPhone 12 }
    { platform:iOS Simulator, id:7D9D5445-2CDA-4C49-866F-FB02D1291B1E, OS:15.2, name:iPhone 12 Pro }
    { platform:iOS Simulator, id:4E260A69-EF58-489E-A485-0F5359FC9A24, OS:15.2, name:iPhone 12 Pro Max }
    { platform:iOS Simulator, id:727DB76F-AE67-4C43-B6F7-6DE43ADD538A, OS:15.2, name:iPhone 12 mini }
    { platform:iOS Simulator, id:77423671-06CA-48A6-B5D5-FAD5889DB7D5, OS:15.2, name:iPhone 13 }
    { platform:iOS Simulator, id:ABC3AA00-75F9-48B3-8C43-6215DE1429CE, OS:15.2, name:iPhone 13 Pro }
    { platform:iOS Simulator, id:15D73476-BF0D-41A2-8DD4-9242E84E3FA5, OS:15.2, name:iPhone 13 Pro Max }
    { platform:iOS Simulator, id:844EB349-580F-4275-BADF-EBE007974FE0, OS:15.2, name:iPhone 13 mini }
    { platform:iOS Simulator, id:EAF9CA67-7FEC-4A70-88AA-A8AF43A1F85D, OS:15.2, name:iPhone SE (2nd generation) }
    { platform:iOS Simulator, id:915432CF-7417-4158-AA28-E90013C4E8B1, OS:15.2, name:iPod touch (7th generation) }
    { platform:iOS, id:dvtdevice-DVTiPhonePlaceholder-iphoneos:placeholder, name:Any iOS Device }
    { platform:iOS Simulator, id:559815E4-D949-496C-86EB-5CF8C6C5B45C, OS:15.2, name:iPad (9th generation) }
    { platform:iOS Simulator, id:CF4908B7-EBE3-4A84-B911-BB4783C62853, OS:15.2, name:iPad Air (4th generation) }
    { platform:iOS Simulator, id:B4E392F9-8BD1-43DC-BD78-1681FCD837A8, OS:15.2, name:iPad Pro (9.7-inch) }
    { platform:iOS Simulator, id:2CD25E32-AACB-41DF-A2DD-BBFCDA91EE11, OS:15.2, name:iPad Pro (11-inch) (3rd generation) }
    { platform:iOS Simulator, id:A1EEB027-10D3-4D45-9DC3-BF280F7F9D2F, OS:15.2, name:iPad Pro (12.9-inch) (5th generation) }
    { platform:iOS Simulator, id:0BB75494-7AAF-4787-8AD1-DD01EC803C13, OS:15.2, name:iPad mini (6th generation) }
    ** BUILD FAILED **


Xcode's output:
↳
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
    Command CompileSwiftSources failed with a nonzero exit code
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:5:34: error: no type named 'SDK' in module 'Jumio'
        fileprivate var jumio: Jumio.SDK?
                                     ^
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:6:36: error: no type named 'ViewController' in module 'Jumio'
        fileprivate var jumioVC: Jumio.ViewController?
                                       ^
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:57:46: error: no type named 'IDResult' in module 'Jumio'
        private func getIDResult(idResult: Jumio.IDResult) -> [String: Any] {
                                                 ^
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:84:50: error: no type named 'FaceResult' in module 'Jumio'
        private func getFaceResult(faceResult: Jumio.FaceResult) -> [String: Any] {
                                                     ^
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:93:37: error: no type named 'DefaultUIDelegate' in module 'Jumio'
    extension JumioModuleFlutter: Jumio.DefaultUIDelegate {
                                        ^
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:94:27: error: no type named 'SDK' in module 'Jumio'
        func jumio(sdk: Jumio.SDK, finished result: Jumio.Result) {
                              ^
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:94:55: error: no type named 'Result' in module 'Jumio'
        func jumio(sdk: Jumio.SDK, finished result: Jumio.Result) {
                                                          ^
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:105:50: error: no type named 'Result' in module 'Jumio'
        private func handleResult(jumioResult: Jumio.Result) {
                                                     ^
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:15:17: error: module 'Jumio' has no member named 'SDK'
            jumio = Jumio.SDK()
                    ^~~~~ ~~~
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:21:34: error: cannot infer contextual base in reference to member 'EU'
                jumio?.dataCenter = .EU
                                    ~^~
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:23:34: error: cannot infer contextual base in reference to member 'SG'
                jumio?.dataCenter = .SG
                                    ~^~
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:25:34: error: cannot infer contextual base in reference to member 'US'
                jumio?.dataCenter = .US
                                    ~^~
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:33:27: error: type of expression is ambiguous without more context
            guard let jumio = jumio else { return }
                              ^~~~~
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:47:29: error: type of expression is ambiguous without more context
            guard let jumioVC = jumioVC else { return }
                                ^~~~~~~
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:49:43: error: cannot infer contextual base in reference to member 'fullScreen'
            jumioVC.modalPresentationStyle = .fullScreen
                                             ~^~~~~~~~~~
    /usr/local/Caskroom/flutter/2.2.3/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:134:43: error: type of expression is ambiguous without more context
                guard let error = jumioResult.error else { return }
                                  ~~~~~~~~~~~~^~~~~
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
    Command CompileSwiftSources failed with a nonzero exit code
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

Could not build the application for the simulator.
Error launching application on iPhone 12.
```

Tried to upgrade or reinstall pods, pubs nothing helped me.
Android running works fine.

 - Device: Iphone 12
 - OS: iOS 15.2 Simulator
 - Flutter SDK Version 2.5.3
 - macOS 12.1 
 - Intel i7

**Comment by bratapfelmus** [comment] 2021-12-27 15:31
Hello @yamaha252,
I know you mention using Flutter version 2.5.3, but error messages indicate version 2.2.3 is still being used in your build attempt: 
`/usr/local/Caskroom/flutter/2.2.3/flutter/...`

If this issue persists, please contact our support.

**Comment by yamaha252** [comment] 2021-12-28 05:35
Yep, the folder was 2.2.3 just because homebrew installed there somehow. I upgraded flutter using internal way and the real version was exactly 2.5.3.
I've reinstalled the cask and now I have the latest version 2.8.1 but the error is same.

```
Launching lib/main_personal_dev.dart on iPhone 12 in debug mode...
Running Xcode build...
Xcode build done.                                           12.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Command CompileSwiftSources failed with a nonzero exit code
    remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:5:34: error: no type named 'SDK' in module 'Jumio'
        fileprivate var jumio: Jumio.SDK?
                                     ^
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:6:36: error: no type named 'ViewController' in module 'Jumio'
        fileprivate var jumioVC: Jumio.ViewController?
                                       ^
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:57:46: error: no type named 'IDResult' in module 'Jumio'
        private func getIDResult(idResult: Jumio.IDResult) -> [String: Any] {
                                                 ^
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:84:50: error: no type named 'FaceResult' in module 'Jumio'
        private func getFaceResult(faceResult: Jumio.FaceResult) -> [String: Any] {
                                                     ^
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:93:37: error: no type named 'DefaultUIDelegate' in module 'Jumio'
    extension JumioModuleFlutter: Jumio.DefaultUIDelegate {
                                        ^
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:94:27: error: no type named 'SDK' in module 'Jumio'
        func jumio(sdk: Jumio.SDK, finished result: Jumio.Result) {
                              ^
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:94:55: error: no type named 'Result' in module 'Jumio'
        func jumio(sdk: Jumio.SDK, finished result: Jumio.Result) {
                                                          ^
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:105:50: error: no type named 'Result' in module 'Jumio'
        private func handleResult(jumioResult: Jumio.Result) {
                                                     ^
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:15:17: error: module 'Jumio' has no member named 'SDK'
            jumio = Jumio.SDK()
                    ^~~~~ ~~~
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:21:34: error: cannot infer contextual base in reference to member 'EU'
                jumio?.dataCenter = .EU
                                    ~^~
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:23:34: error: cannot infer contextual base in reference to member 'SG'
                jumio?.dataCenter = .SG
                                    ~^~
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:25:34: error: cannot infer contextual base in reference to member 'US'
                jumio?.dataCenter = .US
                                    ~^~
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:33:27: error: type of expression is ambiguous without more context
            guard let jumio = jumio else { return }
                              ^~~~~
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:47:29: error: type of expression is ambiguous without more context
            guard let jumioVC = jumioVC else { return }
                                ^~~~~~~
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:49:43: error: cannot infer contextual base in reference to member 'fullScreen'
            jumioVC.modalPresentationStyle = .fullScreen
                                             ~^~~~~~~~~~
    /usr/local/Caskroom/flutter/2.8.1/flutter/.pub-cache/hosted/pub.dartlang.org/jumio_mobile_sdk_flutter-4.0.0/ios/Classes/JumioModuleFlutter.swift:134:43: error: type of expression is ambiguous without more context
                guard let error = jumioResult.error else { return }
                                  ~~~~~~~~~~~~^~~~~
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

Could not build the application for the simulator.
Error launching application on iPhone 12.
```

**Comment by yamaha252** [comment] 2021-12-28 07:24
I also tried to setup a new clean project then installed `jumio_mobile_sdk_flutter` dependency and see the same error in the result.
What extra preparation I should do to make the plugin work?

**Comment by bratapfelmus** [comment] 2021-12-28 08:23
Hello @yamaha252, as stated above please contact support. 
(Make sure to include information on which iOS version / Xcode version you're using if possible.)

**Comment by bratapfelmus** [comment] 2022-01-25 15:25
@yamaha252 upon further investigation, this appears to be an iOS 15 simulator issue and not affect actual devices running with iOS 15. 

In the short term, this should be resolved by setting a specific app language when using the simulator, instead of using system language. 

`Edit scheme > Run > Options > App Language > English (or other language)`

**Comment by yamaha252** [comment] 2022-02-11 07:43
Thank you, @bratapfelmus!
But, I see no effect with region and language changes. I have the same errors with English language set.

**Comment by bratapfelmus** [comment] 2022-02-14 09:21
Hello @yamaha252 
just double checked with the sample app and iOS 15 simulator to make sure -- able to reproduce this issue if App Language isn't set, builds fine if it is. Could you share some steps to reproduce?

**Comment by bratapfelmus** [comment] 2022-02-28 09:10
Closing this because of inactivity. 
@yamaha252 if the issue persists, please contact Jumio support.

**Closed by bratapfelmus** 2022-02-28 09:10 UTC
